version: '3.7'
services:
    navisonic:
        env_file:
            - .env      
        ports:
            - '5000:5000'
        build:
            context: .
            dockerfile: Dockerfile
        image: 'ghcr.io/blinkersfr31/asknavidrome:latest'
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "1"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
